export const PalabrasWeb = {
    auth: {
        brandName: 'Inversiones S&M',
        backgroundAlt: 'Cinematic Futuristic Electric Supercar',
        desktop: {
            portalName: 'Portal logístico B2B',
            accessTitle: 'Acceso de Socios',
            fields: {
                username: {
                    label: 'Número de identidad o RTN',
                    placeholder: '0801-1999-00000',
                },
                password: {
                    label: 'Contraseña',
                    placeholder: '••••••••',
                },
            },
            remember: 'Recordar dispositivo por 30 días',
            forgotPassword: '¿Olvidó su clave?',
            submit: 'Ingresar al portal',
            helper: '¿No tiene una cuenta?',
            requestAccess: 'Solicitar acceso B2B',
            privacy: 'Privacidad',
            terms: 'Términos',
            systemStatus: 'Sistemas en línea',
            support: 'Abrir soporte',
            language: 'Cambiar idioma',
        },
        mobile: {
            portalName: 'Repuestos automotrices premium • Portal B2B',
            accessTitle: 'Iniciar Sesión',
            accessSubtitle: 'Accede temporalmente con tu identidad o RTN',
            fields: {
                email: {
                    label: 'Número de identidad o RTN',
                    placeholder: '0801-1999-00000',
                },
                password: {
                    label: 'Contraseña',
                    placeholder: '••••••••',
                },
            },
            remember: 'Mantener sesión iniciada',
            forgotPassword: '¿Olvidaste?',
            submit: 'Ingresar al portal',
            alternateAccess: 'O accede con',
            helper: '¿No tienes una cuenta de distribuidor?',
            requestAccess: 'Solicitar Registro B2B',
            security: ['Seguridad', 'Cifrado', 'v2.4.0'],
            fingerprint: 'Acceder con huella',
            face: 'Acceder con rostro',
        },
        fields: {
            email: {
                label: 'Número de identidad o RTN',
                placeholder: '0801-1999-00000',
            },
            password: {
                label: 'Contraseña',
                placeholder: '••••••••',
                showPassword: 'Mostrar contraseña',
                hidePassword: 'Ocultar contraseña',
            },
        },
        actions: {
            submit: 'Ingresar al Portal',
            forgotPassword: '¿Olvidaste?',
            requestAccess: 'Solicitar Registro B2B',
            privacy: 'Privacidad',
            terms: 'Términos',
            fingerprint: 'Acceder con huella',
            face: 'Acceder con rostro',
            support: 'Abrir soporte',
            language: 'Cambiar idioma',
        },
        remember: 'Mantener sesión iniciada',
        alternateAccess: 'O accede con',
        helper: '¿No tienes una cuenta de distribuidor?',
        security: 'Seguridad - Cifrado - v2.4.0',
        systemStatus: 'Sistemas en línea',
    },
    portal: {
        brandName: 'Inversiones S&M',
        portalName: 'Portal B2B',
        portalTagline: 'Repuestos automotrices premium',
        navigationLabel: 'Navegación principal del portal',
        mobileNavigationLabel: 'Navegación móvil del portal',
        search: {
            placeholder: 'Buscar repuestos, pedidos o cotizaciones...',
        },
        user: {
            label: 'Usuario activo',
            name: 'Roberto Martínez',
            initials: 'RM',
        },
        actions: {
            newQuote: 'Nueva Cotización',
        },
        sections: {
            metrics: 'Métricas principales',
            focus: 'Vista destacada',
            actions: 'Accesos rápidos',
        },
        quickActionsTitle: 'Operaciones B2B',
        quickActions: [
            { label: 'Nuevo Pedido', href: '/pedidos', icon: '+' },
            { label: 'Cotizar', href: '/cotizaciones', icon: '◇' },
            { label: 'Catálogo', href: '/catalogo', icon: '⌕' },
            { label: 'Soporte', href: '/panel', icon: '?' },
        ],
        routes: {
            dashboard: { href: '/panel' },
            catalog: { href: '/catalogo' },
            brands: { href: '/marcas' },
            orders: { href: '/pedidos' },
            accountStatus: { href: '/estado-de-cuenta' },
            quotes: { href: '/cotizaciones' },
        },
        navigation: [
            { key: 'dashboard', label: 'Panel Principal', shortLabel: 'Inicio', href: '/panel', icon: '⌂' },
            { key: 'catalog', label: 'Catálogo', shortLabel: 'Catálogo', href: '/catalogo', icon: '⌕' },
            { key: 'brands', label: 'Nuestras Marcas', shortLabel: 'Marcas', href: '/marcas', icon: '◇' },
            { key: 'orders', label: 'Mis Pedidos', shortLabel: 'Pedidos', href: '/pedidos', icon: '▣' },
            { key: 'accountStatus', label: 'Estado de Cuenta', shortLabel: 'Cuenta', href: '/estado-de-cuenta', icon: '$' },
            { key: 'quotes', label: 'Cotizaciones', shortLabel: 'Cotizar', href: '/cotizaciones', icon: '□' },
        ],
        mobileNavigation: [
            { key: 'dashboard', label: 'Panel Principal', shortLabel: 'Inicio', href: '/panel', icon: '⌂' },
            { key: 'catalog', label: 'Catálogo', shortLabel: 'Catálogo', href: '/catalogo', icon: '⌕' },
            { key: 'orders', label: 'Mis Pedidos', shortLabel: 'Pedidos', href: '/pedidos', icon: '▣' },
            { key: 'quotes', label: 'Cotizaciones', shortLabel: 'Cotizar', href: '/cotizaciones', icon: '□' },
            { key: 'accountStatus', label: 'Estado de Cuenta', shortLabel: 'Cuenta', href: '/estado-de-cuenta', icon: '$' },
        ],
        support: {
            label: 'Soporte',
            href: '/panel',
        },
        logout: {
            label: 'Cerrar Sesión',
            href: '/login',
        },
    },
    pages: {
        dashboard: {
            code: 'B2B',
            eyebrow: 'Centro de Control',
            title: 'Panel Principal',
            description: 'Resumen ejecutivo de pedidos, crédito disponible y actividad reciente del portal premium.',
            metrics: [
                { label: 'Total Pedidos', value: 'L. 42,850', detail: '+12.5% este mes' },
                { label: 'En Tránsito', value: '18', detail: 'Llegada estimada: 2 días' },
                { label: 'Crédito Disponible', value: 'L. 15,000', detail: '75% de línea activa' },
            ],
            focus: {
                title: 'Rendimiento de cuenta',
                description: 'Vista preparada para integrar indicadores reales del cliente cuando el backend esté disponible.',
                bars: ['42%', '68%', '55%', '88%', '74%', '96%'],
            },
        },
        catalog: {
            code: 'SKU',
            eyebrow: 'Inventario Técnico',
            title: 'Catálogo',
            description: 'Base visual para explorar componentes, filtros, precios B2B y disponibilidad responsive.',
            metrics: [
                { label: 'Componentes', value: '1,420', detail: 'Catálogo activo' },
                { label: 'Marcas Premium', value: '24', detail: 'Aliados certificados' },
                { label: 'Nuevos SKUs', value: '86', detail: 'Últimos 30 días' },
            ],
            focus: {
                title: 'Alta ingeniería automotriz',
                description: 'La siguiente fase convertirá productos y filtros en componentes reutilizables.',
                bars: ['72%', '40%', '85%', '58%', '91%', '64%'],
            },
        },
        brands: {
            code: 'OEM',
            eyebrow: 'Alianzas Estratégicas',
            title: 'Nuestras Marcas',
            description: 'Presentación premium de fabricantes, categorías y beneficios comerciales para clientes B2B.',
            metrics: [
                { label: 'Aliados', value: '+120', detail: 'Fabricantes globales' },
                { label: 'Garantía', value: '100%', detail: 'Producto original' },
                { label: 'SKUs', value: '+50k', detail: 'Inventario directo' },
            ],
            focus: {
                title: 'Red de marcas certificadas',
                description: 'Preparado para cards bento con logos, país, categorías y CTA comercial.',
                bars: ['50%', '80%', '63%', '45%', '78%', '92%'],
            },
        },
        orders: {
            code: 'LOG',
            eyebrow: 'Logística Premium',
            title: 'Mis Pedidos',
            description: 'Seguimiento visual de importaciones, piezas, documentos y estados de entrega.',
            metrics: [
                { label: 'Pedidos Activos', value: '18', detail: '6 prioridad alta' },
                { label: 'Procesados', value: '124', detail: 'Este trimestre' },
                { label: 'Tiempo Promedio', value: '4.2d', detail: 'Despacho nacional' },
            ],
            focus: {
                title: 'Timeline de cumplimiento',
                description: 'La siguiente fase agregará una línea de progreso adaptable a desktop y mobile.',
                bars: ['24%', '48%', '67%', '83%', '56%', '91%'],
            },
        },
        accountStatus: {
            code: 'FIN',
            eyebrow: 'Control Financiero',
            title: 'Estado de Cuenta',
            description: 'Resumen de crédito, pagos, vencimientos y movimientos del cliente B2B.',
            metrics: [
                { label: 'Deuda Total', value: 'L. 42,850', detail: 'Vence en 5 días' },
                { label: 'Crédito Disponible', value: 'L. 15,150', detail: '75% utilizado' },
                { label: 'Último Pago', value: 'L. 5,200', detail: 'Recibido el 12 Oct' },
            ],
            focus: {
                title: 'Flujo financiero anual',
                description: 'Base para gráficos CSS/SVG sin librerías externas.',
                bars: ['36%', '64%', '82%', '45%', '70%', '93%'],
            },
        },
        quotes: {
            code: 'QTE',
            eyebrow: 'Gestión Comercial',
            title: 'Cotizaciones',
            description: 'Administración de solicitudes, estados, importes y acciones comerciales.',
            metrics: [
                { label: 'Total Cotizaciones', value: '148', detail: '+12% este mes' },
                { label: 'Pendientes', value: '24', detail: '4 activas' },
                { label: 'Aprobadas', value: '112', detail: '85% éxito' },
            ],
            focus: {
                title: 'Pipeline de cotización',
                description: 'Preparado para tabla desktop y cards mobile en la fase de detalle.',
                bars: ['66%', '52%', '74%', '38%', '90%', '60%'],
            },
        },
    },
};
